export const USERS = [
  { id:'u1',  prenom:'BOUA',      nom:'Bahi',        email:'directeur@cadastre.dgi.ci',      role:'directeur',      serviceId:null,  statut:'actif'      },
  { id:'u2',  prenom:'COMOE',     nom:'Lucien',      email:'conseiller1@cadastre.dgi.ci',    role:'conseiller_tech',serviceId:null,  statut:'actif'      },
  { id:'u3',  prenom:'TIMITEY',   nom:'Maury',       email:'conseiller2@cadastre.dgi.ci',    role:'conseiller_tech',serviceId:null,  statut:'actif'      },
  { id:'u4',  prenom:'DIOMANDE',  nom:'Messou',      email:'sd.information@cadastre.dgi.ci', role:'sous_directeur', serviceId:null,  statut:'actif'      },
  { id:'u5',  prenom:'DOUMBIA',   nom:'Tayomou',     email:'sd.production@cadastre.dgi.ci',  role:'sous_directeur', serviceId:null,  statut:'actif'      },
  { id:'u6',  prenom:'BLON',      nom:'Sadia',       email:'sd.assiette@cadastre.dgi.ci',    role:'sous_directeur', serviceId:null,  statut:'actif'      },
  { id:'u7',  prenom:'KONE',      nom:'Souleymane',  email:'sd.evaluation@cadastre.dgi.ci',  role:'sous_directeur', serviceId:null,  statut:'actif'      },
  { id:'u8',  prenom:'Georgette', nom:'GBAGBO',      email:'secretariat@cadastre.dgi.ci',    role:'secretariat',    serviceId:null,  statut:'actif'      },
  { id:'u9',  prenom:'Kofi',      nom:'MENSAH',      email:'chef.safic@cadastre.dgi.ci',     role:'chef_service',   serviceId:'s0',  statut:'actif'      },
  { id:'u10', prenom:'MAHE',      nom:'Thomas',      email:'chef.spse@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s1',  statut:'actif'      },
  { id:'u11', prenom:'DJABIA',    nom:"N'goran",     email:'chef.sesc@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s2',  statut:'actif'      },
  { id:'u12', prenom:'BAH',       nom:'Blegnon',     email:'chef.scoa@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s3',  statut:'actif'      },
  { id:'u13', prenom:'LEAN',      nom:'Jessyca',     email:'chef.sar@cadastre.dgi.ci',       role:'chef_service',   serviceId:'s4',  statut:'actif'      },
  { id:'u14', prenom:'SERI',      nom:'Ange',        email:'chef.src@cadastre.dgi.ci',       role:'chef_service',   serviceId:'s5',  statut:'actif'      },
  { id:'u15', prenom:'HIA BI',    nom:'Arthur',      email:'chef.sctf@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s6',  statut:'actif'      },
  { id:'u16', prenom:'KOSSONOU',  nom:'Patrice',     email:'chef.scafr@cadastre.dgi.ci',     role:'chef_service',   serviceId:'s7',  statut:'actif'      },
  { id:'u17', prenom:"N'DA",      nom:'Amani',       email:'chef.sep@cadastre.dgi.ci',       role:'chef_service',   serviceId:'s8',  statut:'actif'      },
  { id:'u18', prenom:'BOA',       nom:'Thiémélé',    email:'chef.sdic@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s9',  statut:'actif'      },
  { id:'u19', prenom:'MISSA',     nom:'Therenot',    email:'chef.sspda@cadastre.dgi.ci',     role:'chef_service',   serviceId:'s10', statut:'actif'      },
  { id:'u20', prenom:'MAYOU',     nom:'Boris',       email:'chef.scr@cadastre.dgi.ci',       role:'chef_service',   serviceId:'s11', statut:'actif'      },
  { id:'u21', prenom:'Rodrigue',  nom:'KONAN',       email:'chef.sei@cadastre.dgi.ci',       role:'chef_service',   serviceId:'s12', statut:'actif'      },
  { id:'u22', prenom:'BOA',       nom:'Thiémélé',    email:'chef.sefr@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s13', statut:'actif'      },
  { id:'u23', prenom:'COULIBALY', nom:'Wanna',       email:'chef.svcr@cadastre.dgi.ci',      role:'chef_service',   serviceId:'s14', statut:'actif'      },
  { id:'u24', prenom:'Jean',      nom:'KOUAKOU',     email:'admin@cadastre.dgi.ci',          role:'admin',          serviceId:null,  statut:'actif'      },
  { id:'u25', prenom:'Ibrahim',   nom:'COUL.',       email:'attente@cadastre.dgi.ci',        role:'chef_service',   serviceId:'s12', statut:'en_attente' },
];
